// AUTHENTICATION
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';

// PROFILE USER
export const SET_PROFILE_USER = 'SET_PROFILE_USER';
export const CLEAR_PROFILE_USER = 'CLEAR_PROFILE_USER';
export const SET_PROFILE_POSTS = 'SET_PROFILE_POSTS';
export const CLEAR_PROFILE_POSTS = 'CLEAR_PROFILE_POSTS';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const UPDATE__CURRENT_USER_PASSWORD = 'UPDATE__CURRENT_USER_PASSWORD';
export const DELETE_CURRENT_USER = 'DELETE_CURRENT_USER';
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const SET_PROFILE_ERROR = 'SET_PROFILE_ERROR';

// POSTS
export const GET_POSTS = 'GET_POSTS';
export const GET_POPULAR_POSTS = 'GET_POPULAR_POSTS';
export const GET_RECOMMENDED_POSTS = 'GET_RECOMMENDED_POSTS';
export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const SET_CURRENT_POST = 'SET_CURRENT_POST';
export const CLEAR_CURRENT_POST = 'CLEAR_CURRENT_POST';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';
export const FILTER_POSTS = 'FILTER_POSTS';
export const CLEAR_FILTER_POSTS = 'CLEAR_FILTER_POSTS';
export const SET_LOADING_POSTS = 'SET_LOADING_POSTS';
export const SET_POSTS_ERROR = 'SET_POSTS_ERROR'


// THEME
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SET_ACTIVE_DROPDOWN = 'SET_ACTIVE_DROPDOWN';
export const SET_ACTIVE_MENU = 'SET_ACTIVE_MENU'